help :-
        write('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'), nl,
        write('%                                 ~ARCANE~                                      %'), nl,
        write('% 1.  start  : untuk memulai petualanganmu                                      %'), nl,
        write('% 2.  map    : menampilkan peta                                                 %'), nl, 
        write('% 3.  status : menampilkan kondisimu terkini                                    %'), nl,
        write('% 4.  w      : gerak ke atas 1 langkah                                          %'), nl,
        write('% 5.  s      : gerak ke bawah 1 langkah                                         %'), nl,
        write('% 6.  d      : gerak ke kanan 1 langkah                                         %'), nl,
        write('% 7.  a      : gerak ke kiri 1 langkah                                          %'), nl,
        write('% 8.  quest  : memeriksa quest yang sedang berjalan                             %'), nl,
        write('% 9.  ranch  : melakukan ternak (harus dilakukan di \'R\')                        %'), nl,
        write('% 10. fish   : memancing ikan (harus dilakukan di sekitar air \'o\')              %'), nl,
        write('% 11. dig    : membuat tiles yang siap ditanam                                  %'), nl,
        write('% 12. plant  : menanam tumbuhan (harus dilakukan di \'=\')                        %'), nl,
        write('% 13. harvest: memanen tumbuhan (harus dilakukan di tumbuhan)                   %'), nl,
        write('% 14. exit   : keluar dari permainan (tidak menyimpan state dari game)          %'), nl,
        write('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'), nl.